version: '3.8'

services:
  backend:
    image: backend-fast
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    image: frontend-clg
    container_name: frontend
    ports:
      - 9000:80